### ISSUE TITLE
dig does not work when an the first nameserver configured is ipv6.

### ISSUE THREAD

**Issue by damm** [mehrdadrad/mylg#17]
local> dig likens.us
Trying to query server: 2001:558:feed::1  your local dns server
dial udp: too many colons in address 2001:558:feed::1:53

When modifying /etc/resolv.conf to put 8.8.8.8 in front it works...

**Comment by mehrdadrad** [comment]
Thank you for reporting this issue. it fixed at repo and will be released soon at next version.

**Comment by damm** [comment]
Thank you for the quick response.
