### ISSUE TITLE
scan - be tolerant with "too many open files"

### ISSUE THREAD

**Issue by jfesler** [mehrdadrad/mylg#22]
I'm reviewing scan/scan.go.

I have a feature request:

When calling `net.DialTimeout`, if you get an error that says "too many open files", pause that go routine and then retry.

If you do that, you'll be able to reduce the 8ms sleep.  Additionally, if you do that, your tool will be robust when doing large scans in environments with restrictive ulimits.

Unfortunately, I am _unable_ to contribute a similar PR for your scanner.  My current employer's rules of engagement prohibit it; and I'm not ready to change employers. (sadface!)

**Comment by mehrdadrad** [comment]
Thank you for reviewing, appreciated.
I'll be enhanced it soon.
