### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by msenturk** [mehrdadrad/mylg#33]

**Comment by jbull328** [comment]
I was able to install it on my windows 10 pc through the Bash shell. This can be done with some simple instructions. Similar to the Ubuntu Debian install instructions.

**Comment by gummiboll** [comment]
Or run it with [docker](https://github.com/mehrdadrad/mylg/blob/master/Dockerfile).

**Comment by mehrdadrad** [comment]
Bash on Ubuntu on Windows
https://msdn.microsoft.com/en-us/commandline/wsl/about

**Comment by msenturk** [comment]
Yes Bash on Windows is good idea. thanks
