### ISSUE TITLE
trace panic in external lg mode

### ISSUE THREAD

**Issue by peterrosell** [mehrdadrad/mylg#36]
Just install this nice tool and played around for awhile and noticed that I got a panic when trying to do trace on external looking glass mode. It works correct in local mode.

```
local> lg
lg> trace www.google.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x404a82]

goroutine 1 [running]:
panic(0x8fd8e0, 0xc42000c180)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.trace()
	/home/vagrant/golang/src/github.com/mehrdadrad/mylg/mylg.go:312 +0xb2
main.main()
	/home/vagrant/golang/src/github.com/mehrdadrad/mylg/mylg.go:157 +0x1e6
```

**Comment by mehrdadrad** [comment]
Thank you for reporting this bug. once the lg selected user needs to connect to a provider like telia then a node (like Los Angeles). I'll commit a code to set  a default to cover this issue.
