### ISSUE TITLE
Issue with IPv6 targets.

### ISSUE THREAD

**Issue by rboissat** [mehrdadrad/mylg#37]
Hi!

When trying to trace hostnames resolving to a IPv6 AAAA, I got the following error:

`dial udp: too many colons in address 2001:db8:a:b::1:80`

Indeed, the far right ":80" is the transport layer port number. I am currently using the most current osx binary available on your website.

Thanks!

**Comment by mehrdadrad** [comment]
Thank you for reporting this issue. It should be fixed please try again and let me know if you're still seeing this issue. I'll update the binary / packages later soon.

**Comment by rboissat** [comment]
@mehrdadrad Thanks a lot for your quick feedback! Unfortunately, I can't easily test from source, but I can set up an IPv6 enabled VM with Go environment to test out if you want to delay the binary release according to this issue.
