### ISSUE TITLE
install instructions

### ISSUE THREAD

**Issue by jungle-boogie** [mehrdadrad/mylg#38]
Hi There,

First, thank you for creating this tool. It's very nice and I'm presently surprised to see it written in go.

There must be a reason your install instructions explain a bit longer way to install your project from source. What's the reason?

`go get github.com/mehrdadrad/mylg` would work just fine.

Additionally, I recommend updating the install instructions here http://mylg.io/doc/ to indicate you need to copy to /usr/local/sbin (at least on FreeBSD)
Currently you have:
`curl -O http://mylg.io/dl/freebsd/mylg && chmod +x mylg && mv mylg /usr/bin/`

*BSD's put base installed applications in `/usr/` whereas installed packages go `/usrl/local`. I say sbin as well because you need elevated privileges to use mylg:

```
local> ping yahoo.com
PING yahoo.com (2001:4998:58:c02::a9): 56 data bytes
listen ip6:ipv6-icmp : socket: operation not permitted icmp_seq=0
listen ip6:ipv6-icmp : socket: operation not permitted icmp_seq=0
listen ip6:ipv6-icmp : socket: operation not permitted icmp_seq=0
listen ip6:ipv6-icmp : socket: operation not permitted icmp_seq=0

--- yahoo.com ping statistics ---
4 packets transmitted,  0 packets received, 100% packet loss 
```

**Comment by mehrdadrad** [comment]
@jungle-boogie  I agree w/ go get github.com/mehrdadrad/mylg I was thinking about updating the readme but as you opened this issue I'll update it soon.
what do you think about the below:
curl -O http://mylg.io/dl/freebsd/mylg && chmod u+s,+x mylg && mv mylg /usr/local/sbin

**Comment by jungle-boogie** [comment]
hi @mehrdadrad,

I'm okay with the readme that you changed. I don't know what exactly `go run mylg` does. Once it's completed building on my machine, I copy it from `$GOPATH/bin` to `~/bin` as I bin as a search path.

better yet:
`curl -O http://mylg.io/dl/freebsd/mylg && chmod u+s,+x mylg && sudo mv mylg /usr/local/sbin`
