### ISSUE TITLE
hping display port

### ISSUE THREAD

**Issue by jungle-boogie** [mehrdadrad/mylg#44]
Hi,

I think it would be really useful to have hping support an option for a destination port.

```
local> hping http://192.168.0.17:8080 -c 1
HPING 192.168.0.17 (192.168.0.17), Method: HEAD, DNSLookup: 0.0207 ms
HTTP Response seq=0, proto=HTTP/1.0, status=404, time=8.066 ms

--- 192.168.0.17 HTTP ping statistics ---
1 requests transmitted, 1 replies received, 0% requests failed
HTTP Round-trip min/avg/max = 8.07/8.07/8.07 ms
HTTP Code [404] responses : [████████████████████] 100.00%
```

**Comment by mehrdadrad** [comment]
what's the advantage of the option for dst port?
@gummiboll what do you think?

**Comment by gummiboll** [comment]
Would be easy to implement, but I have to admit I don't really see why?

Maybe I'm dense or missing something here but isn't it easier/more straight forward to specify this in the url, ie: ```http(s)://hostname:port``` (which already works) than having a extra option for it?

**Comment by jungle-boogie** [comment]
Hi @mehrdadrad, @gummiboll,

But `HPING 192.168.0.17 (192.168.0.17),` doesn't contain the port and you can see I specified a port in my request.

**Comment by gummiboll** [comment]
Ah, yeah. You're correct about that. The actual request is sent to the correct port but the banner (HPING hostname (IP.ADDR)) doesn't reflect that. I will fix that tomorrow if @mehrdadrad doesn't beat me to it.

**Comment by mehrdadrad** [comment]
@gummiboll Thanks Emil!

**Comment by gummiboll** [comment]
Submitted a PR for this, good catch @jungle-boogie !

**Comment by jungle-boogie** [comment]
very nice! 
thank you, @gummiboll 
`HPING 192.168.0.17:8080 (192.168.0.17), Method: HEAD, DNSLookup: 0.0193 ms`
