### ISSUE TITLE
set Snmp community

### ISSUE THREAD

**Issue by nebi** [mehrdadrad/mylg#49]
Hi ,

When you set the snmp community with command `set snmp community testSnmp` it will make the community name to lowercase. 

log from router : 
`
snmpd[1698]: SNMPD_AUTH_FAILURE: nsa_log_community: unauthorized SNMP community from 1xx.xx.xxx.1 to 1xx.xx.x.2 (testsnmp)
`
If you use the command : ` connect 1xx.xxx.x.2 -c testSnmp` it works. 

I also checked the config file and see that the community is in lowercase. 

I use the latest version.

**Comment by nebi** [comment]
Probaly this in file cli/cli.go (row 151)

`
// SetPrompt set readline prompt and store it
func (r *Readline) SetPrompt(p string) {
        p = strings.ToLower(p)
        r.prompt = p
        r.instance.SetPrompt(p + "> ")
}
`

**Comment by mehrdadrad** [comment]
@nebi Thank you for reporting this issue. it should be fixed at the code base.
