### ISSUE TITLE
Inconceivable result in concurrent-mtr jobs

### ISSUE THREAD

**Issue by EverChris** [mehrdadrad/mylg#56]
I used your code and compared with linux mtr, the result is same, very good!

but when I run **more than 10 mtr jobs concurrently**, the result is inconceivable,

![](http://ww4.sinaimg.cn/large/6df1da21gw1fachclggqkj20pw0k7e1n.jpg)
![](http://ww4.sinaimg.cn/large/6df1da21gw1fachcxfb9rj20ts062jxw.jpg)

Look, ```the first picture is concurrent-mtr test```, ```the second picture is single-mtr test```.

Lets compare the same target ```183.131.7.137```, the first result is mostly different with the second one. In fact, the second result is expected.

And there isn't this problem of linux mtr.

Thx!

**Comment by mehrdadrad** [comment]
@EverChris I think that's related to ID: os.Getpid()
try to use different ID for each goroutine

**Comment by EverChris** [comment]
@mehrdadrad I tried random `id` for every connects, but it didn't works.

I even tried different `seq`. 

I also tried multi-process (not goroutine) to run concurrent-mtr jobs in one machine.

But if I add a locker to the icmp-connect, it works.

How do u think, any other idea?

Thanks for your attention.

**Comment by mehrdadrad** [comment]
What protocol you tried? icmp or udp

**Comment by EverChris** [comment]
@mehrdadrad 

icmp

there is another problem of mtr-udp, forget it.

**Comment by mehrdadrad** [comment]
please send me the code which you're trying to my email address

**Comment by EverChris** [comment]
Hi sir,

this is the example code, i used your code below and added a few settings to them.

```
mylg/cli
mylg/icmp
```

My only target is to do concurrent-mtr jobs to more than 30 IPs.

Very thanks to your code, nice of you!

2016-12-06 

Chris



发件人：Mehrdad Arshad Rad <notifications@github.com>
发送时间：2016-12-06 15:47
主题：Re: [mehrdadrad/mylg] Inconceivable result in concurrent-mtr jobs (#56)
收件人："mehrdadrad/mylg"<mylg@noreply.github.com>
抄送："Nova"<lvzhuo1213@gmail.com>,"Mention"<mention@noreply.github.com>

please send me the code which you're trying to my email address

**Comment by EverChris** [comment]
hello, sorry to bother you again.

is there any problem in that code?

2016-12-07 

lvzhuo1213 



发件人：Mehrdad Arshad Rad <notifications@github.com>
发送时间：2016-12-06 15:47
主题：Re: [mehrdadrad/mylg] Inconceivable result in concurrent-mtr jobs (#56)
收件人："mehrdadrad/mylg"<mylg@noreply.github.com>
抄送："Nova"<lvzhuo1213@gmail.com>,"Mention"<mention@noreply.github.com>

please send me the code which you're trying to my email address

**Comment by mehrdadrad** [comment]
I can not see the code. you sent the below:

```
mylg/cli
mylg/icmp
```

**Comment by EverChris** [comment]
The code was in the attactment.

I send the code in the attactment again this time.

2016-12-08 

lvzhuo1213 



发件人：Mehrdad Arshad Rad <notifications@github.com>
发送时间：2016-12-07 23:59
主题：Re: [mehrdadrad/mylg] Inconceivable result in concurrent-mtr jobs (#56)
收件人："mehrdadrad/mylg"<mylg@noreply.github.com>
抄送："Nova"<lvzhuo1213@gmail.com>,"Mention"<mention@noreply.github.com>

I can not see the code. you sent the below:
mylg/cli
mylg/icmp

**Comment by mehrdadrad** [comment]
still, I can not see the source code (no attachment) pls email me the github address or your code to arshad.rad@gmail.com
