### ISSUE TITLE
increase scan port range

### ISSUE THREAD

**Issue by jungle-boogie** [mehrdadrad/mylg#59]
Thanks to the hard work of @gummiboll and @mehrdadrad, #46 is working much better!

This is a request to increase scan range from:
1-500
to
**1-1024**

<1024 will require root to run so it's beneficial to see what else is listening to those lower ports.

**Comment by mehrdadrad** [comment]
@jungle-boogie right, feel free to change it.

**Comment by jungle-boogie** [comment]
I see %s referencing the 1-500, but I don't see where to increase the range. Can you give me a hint?

**Comment by gummiboll** [comment]
@jungle-boogie: It comes from the config. The default config (which is written if no config file exists) is [here](https://github.com/mehrdadrad/mylg/blob/master/cli/config.go#L31)

**Comment by jungle-boogie** [comment]
Thanks!

https://github.com/mehrdadrad/mylg/pull/60
