### ISSUE TITLE
Proposal: make the different utilities directly accessible from the shell

### ISSUE THREAD

**Issue by MoritzFago** [mehrdadrad/mylg#6]
If you follow the unix philosophy that every program should do only one thing but that very good it would be nice if you would consider to create subcommands or different binaries for every tool. This would reduce the necessary steps to use trace from two (`mylg` and then `trace foo.ba`) to one (either `trace foo.bar` or `mylg trace foo.bar`)

**Comment by mehrdadrad** [comment]
Thanks @MoritzFago but I added this feature recently but not yet released. the code available at github.
