### ISSUE TITLE
don't exit trace -r -c 5

### ISSUE THREAD

**Issue by jungle-boogie** [mehrdadrad/mylg#64]
Hi All,

`trace freebsd.org -c 10 -r` will correct traceroute to the host ten times but then immediately close once the tenth scan is finished. Is it possible to keep the results open to review them, or cat it to standard out and return to mylg prompt?

**Comment by mehrdadrad** [comment]
@jungle-boogie Righ it should be stopped, just you need to remove the below line from icmp/trace_termui.go
```
- 110 ui.StopLoop()
```
BTW there is a hidden switch -R for reporting, if you like you can add it to the help.

**Comment by mehrdadrad** [comment]
fixed by PR #65
