### ISSUE TITLE
change config path: PR #66

### ISSUE THREAD

**Issue by jungle-boogie** [mehrdadrad/mylg#67]
Hi All,

This is regarding pull request https://github.com/mehrdadrad/mylg/pull/66

There's discussion on the table to move `~/.mylg.config` to `~/.config/mylg/mylg.config` and how to handle this on existing mylg installs.

**Comment by mehrdadrad** [comment]
I'm not against of this new location but that's not a priority.
Still, vim config is under ~/.vimrc

**Comment by mehrdadrad** [comment]
I like this new location but that's not a priority.
Still, vim config is under ~/.vimrc

**Comment by jungle-boogie** [comment]
> Still, vim config is under ~/.vimrc

My .vimrc is actually at ~/ but `~/.vim` contains my plugins.

What's the concern with it being moved to `~/.config`?

Apparently there's something called XDG and there's basically a standard for app configs to be listed in `~/.config`:
http://unix.stackexchange.com/questions/24347/why-do-some-applications-use-config-appname-for-their-config-data-while-other

https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html

If you use *BSD or GNU/Linux as a desktop OS, take a peak at your `~/.config` and see what all is stored there.

**Comment by jungle-boogie** [comment]
> that's not a priority.

Sure, keep the PR open as long as you'd like.

**Comment by gummiboll** [comment]
My $0.02:

I do like the idea of many applications storing their configuration in one place and I have nothing against the idea of moving the configuration file for mylg to it but with that said, the mentioned standard is a standard from freedesktop and it isn't followed/acknowledged by everyone from my understanding. The only application that has stored files in .config on my laptop is atom.

I don't really mind having dotfiles in my ~ and if I would change laptop and forget (which I'm sure I will) to bring my .mylg.config, it doesn't really matter that much too me, I have nothing backup-worthy in it. I kinda see dotfiles as throwaways, easily recreated if needed.

I.e: I'm not against the idea but I don't see a big payoff from the change either.

**Comment by jungle-boogie** [comment]
> the mentioned standard is a standard from freedesktop and it isn't followed/acknowledged by everyone from my understanding.

both points are very true. Like most standards, it's something that should be followed but it won't cause harm if it's not followed. For instance, I wish my employer would standardize the data format to ISO 8601 (YYYY-MM-DD), but there's very little harm for having the data in the typical US fashion of MM/DD/YYYY or the European DD-MM-YYYY or even a mix of all three.

> The only application that has stored files in .config on my laptop is atom.

Well without knowing what applications you have installed, that doesn't tell us much. On my trueos system, I have these:
```
autostart
dconf
gtk-3.0
lumina-desktop
lumina-mimeapps.list
mimeapps.list
pavucontrol.ini
PCBSD
PCBSD.conf
pulse
qtcurve
qtcurve.gtk-icons
QtProject.conf
sqlitebrowser
tilda
user-dirs.dirs
vlc
wireshark
```

> I kinda see dotfiles as throwaways, easily recreated if needed.

I do for most of what's above. I especially do with `mylg` because the settings take 2 seconds to set. The only setting I may change is the web port and IP address. Other files are likely in some kind of version control where I check them out, edit them and check them back in. (like with RCS).

> I.e: I'm not against the idea but I don't see a big payoff from the change either.

I wasn't proposing a big payoff, only a somewhat understood standard.

**Comment by gummiboll** [comment]
Maybe 'big payoff' was the wrong set of words. Don't get me wrong, I think it is a good idea to have it in .config.

But don't get me started on the US date format. MM/DD/YYYY is just.. _absurd_. :P
