### ISSUE TITLE
Build error invalid argument r.snaplen (type uint32) for len

### ISSUE THREAD

**Issue by looterz** [mehrdadrad/mylg#7]
Happens when running go get or go build.

Debian 8.5 x64 

```
# github.com/google/gopacket/pcapgo
../../google/gopacket/pcapgo/read.go:124: invalid argument r.snaplen (type uint32) for len
```

**Comment by mehrdadrad** [comment]
what's your libpcap version?

**Comment by mehrdadrad** [comment]
I could be able to duplicate this issue, looks the github gopacket updated 8 hours ago w/ a bug at read.go, i just opened an issue #225 google.com/gopacket

**Comment by looterz** [comment]
libpcap-dev is 1.6.2-2

**Comment by tasdomas** [comment]
This seems to be a go version related issue. Build fails with go 1.6, succeeds with go 1.7

**Comment by mathewcrane** [comment]
I get the same issue on Fedora 23

golang-1.5.4-3.fc23.x86_64
golang-src-1.5.4-3.fc23.noarch
golang-bin-1.5.4-3.fc23.x86_64
libpcap-devel-1.7.4-1.fc23.x86_64
libpcap-1.7.4-1.fc23.x86_64

**Comment by mehrdadrad** [comment]
fixed by google w/ below commit:
https://github.com/google/gopacket/commit/1b746f68116cb7c7ada4625eb718cf45e67dc31a

**Comment by mathewcrane** [comment]
Fixed, build now works after removing $GOPATH/src/github.com/google/gopacket/ and rerunning 'go get' in the mylg folder.
