### ISSUE TITLE
missing packages

### ISSUE THREAD

**Issue by peterpt** [mehrdadrad/mylg#71]
i did "go get" inside mylg to get the missing packages  , but some are unavailable ?!!
when i do "go build mylg.go" i get 2 missing packages 

/usr/lib/go/src/pkg/github.com/mehrdadrad/mylg/http/ping/ping.go:6:2: import "context": cannot find package

and 

/usr/lib/go/src/pkg/github.com/mehrdadrad/mylg/http/ping/ping.go:14:2: import "net/http/httptrace": cannot find package`

**Comment by mehrdadrad** [comment]
@peterpt Go version 1.7 or greater is required
