### ISSUE TITLE
other options on web interface

### ISSUE THREAD

**Issue by peterpt** [mehrdadrad/mylg#75]
Is there a way to web interface have more options than ping and trace only  ?
according to terminal on lg we have scan , whois , dig and local discovery that could be implemented on web interface .
Is there a way to  put those options there or am i missing something and it is only possible to use those commands over the terminal ?

**Comment by mehrdadrad** [comment]
web interface already has two features: ping and trace, I created the web UI as a prototype and I would love someone to continue and add more back-end features to UI. the current UI tech is AngularJS-2 if someone contributed to this part I could create the APIs super quick. anyway looking for UI contributor.

**Comment by peterpt** [comment]
Basically every tool that mylg have on terminal we already have it by default on linux terminal using multiple tools : traceroute , dig , nmap , speedtest_cli , tcpdump , etc... .
It would be the cherry on the top of the cake if someone could hep you out with this work .
Unhappily i am not the person with that knowledge , but i will give a look into the code to see how you did traceroute , because the same model can be used for dig and port scanning at least .
Thanks for the info .
