### ISSUE TITLE
mylg.io

### ISSUE THREAD

**Issue by smnmtzgr** [mehrdadrad/mylg#79]
Hi,

is this project still actively maintained? mylg.io is down and there were no commits since a few months.
I like mylg very much thats why I ask!

Regards,
Simon

**Comment by mehrdadrad** [comment]
@smnmtzgr mylg.io is up and running. I involve to other projects like [vFlow](https://github.com/VerizonDigital/vflow) but if there is bug I'll try to fix it.
I'm glad you like it 👍

**Comment by mehrdadrad** [comment]
@smnmtzgr mylg.io is up and running. I'm busy w/ other projects like [vFlow](https://github.com/VerizonDigital/vflow) but if there is bug I'll try to fix it.
I'm glad you like it 👍
